#!/usr/bin/env python
"""
Abaqus Input File Generator for Acoustic Transmission Loss
=========================================================

This script generates Abaqus .inp files directly for acoustic transmission loss
simulation without using the CAE interface. Useful for batch processing and
automated parameter studies.

Author: Generated for acoustic transmission loss analysis
Date: 2024
"""

import numpy as np
import math

class AbaqusInputGenerator:
    """Generate Abaqus .inp files for acoustic simulations"""
    
    def __init__(self, filename="acoustic_simulation.inp"):
        self.filename = filename
        self.lines = []
        
    def write_line(self, line=""):
        """Write a line to the input file"""
        self.lines.append(line)
        
    def write_comment(self, comment):
        """Write a comment line"""
        self.lines.append(f"** {comment}")
        
    def write_heading(self, title="Acoustic Transmission Loss Simulation"):
        """Write file heading"""
        self.write_line("*HEADING")
        self.write_line(f"** {title}")
        self.write_line("** Generated by Abaqus Python script")
        self.write_line("** Units: m, kg, s, Pa")
        self.write_line("")
        
    def write_materials(self, materials):
        """Write material definitions"""
        self.write_comment("MATERIAL DEFINITIONS")
        self.write_line("")
        
        for i, material in enumerate(materials):
            mat_name = f"ACOUSTIC_{i+1}"
            self.write_line(f"*MATERIAL, NAME={mat_name}")
            self.write_line("*DENSITY")
            self.write_line(f"{material['density']:.1f},")
            self.write_line("*BULK MODULUS")
            self.write_line(f"{material['bulk_modulus']:.6e},")
            self.write_line("")
            
    def write_gradient_material(self, base_density, base_bulk_modulus, 
                              density_gradient, bulk_modulus_gradient, 
                              z_range=(0, 2), n_points=20):
        """Write material with field variable dependencies"""
        self.write_comment("GRADIENT MATERIAL WITH FIELD VARIABLE DEPENDENCIES")
        self.write_line("")
        
        self.write_line("*MATERIAL, NAME=ACOUSTIC_GRADIENT")
        
        # Density table
        self.write_line("*DENSITY, DEPENDENCIES=1")
        z_values = np.linspace(z_range[0], z_range[1], n_points)
        for z in z_values:
            density = base_density + density_gradient * z
            self.write_line(f"{z:.3f}, {density:.1f}")
        self.write_line("")
        
        # Bulk modulus table
        self.write_line("*BULK MODULUS, DEPENDENCIES=1")
        for z in z_values:
            bulk_modulus = base_bulk_modulus + bulk_modulus_gradient * z
            self.write_line(f"{z:.3f}, {bulk_modulus:.6e}")
        self.write_line("")
        
    def write_nodes_2d(self, length, width, element_size):
        """Generate 2D node coordinates"""
        self.write_comment("NODE DEFINITIONS (2D)")
        self.write_line("*NODE")
        
        nx = int(length / element_size) + 1
        ny = int(width / element_size) + 1
        
        node_id = 1
        for j in range(ny):
            y = j * element_size
            for i in range(nx):
                x = i * element_size
                self.write_line(f"{node_id}, {x:.6f}, {y:.6f}")
                node_id += 1
                
        self.write_line("")
        return nx, ny
        
    def write_nodes_3d(self, length, width, height, element_size):
        """Generate 3D node coordinates"""
        self.write_comment("NODE DEFINITIONS (3D)")
        self.write_line("*NODE")
        
        nx = int(length / element_size) + 1
        ny = int(width / element_size) + 1
        nz = int(height / element_size) + 1
        
        node_id = 1
        for k in range(nz):
            z = k * element_size
            for j in range(ny):
                y = j * element_size
                for i in range(nx):
                    x = i * element_size
                    self.write_line(f"{node_id}, {x:.6f}, {y:.6f}, {z:.6f}")
                    node_id += 1
                    
        self.write_line("")
        return nx, ny, nz
        
    def write_elements_2d(self, nx, ny, element_type="AC2D4"):
        """Generate 2D acoustic elements"""
        self.write_comment("ELEMENT DEFINITIONS (2D)")
        self.write_line(f"*ELEMENT, TYPE={element_type}")
        
        elem_id = 1
        for j in range(ny - 1):
            for i in range(nx - 1):
                # 4-node quadrilateral
                n1 = j * nx + i + 1
                n2 = j * nx + i + 2
                n3 = (j + 1) * nx + i + 2
                n4 = (j + 1) * nx + i + 1
                
                self.write_line(f"{elem_id}, {n1}, {n2}, {n3}, {n4}")
                elem_id += 1
                
        self.write_line("")
        return elem_id - 1
        
    def write_elements_3d(self, nx, ny, nz, element_type="AC3D8"):
        """Generate 3D acoustic elements"""
        self.write_comment("ELEMENT DEFINITIONS (3D)")
        self.write_line(f"*ELEMENT, TYPE={element_type}")
        
        elem_id = 1
        for k in range(nz - 1):
            for j in range(ny - 1):
                for i in range(nx - 1):
                    # 8-node hexahedron
                    n1 = k * nx * ny + j * nx + i + 1
                    n2 = k * nx * ny + j * nx + i + 2
                    n3 = k * nx * ny + (j + 1) * nx + i + 2
                    n4 = k * nx * ny + (j + 1) * nx + i + 1
                    n5 = (k + 1) * nx * ny + j * nx + i + 1
                    n6 = (k + 1) * nx * ny + j * nx + i + 2
                    n7 = (k + 1) * nx * ny + (j + 1) * nx + i + 2
                    n8 = (k + 1) * nx * ny + (j + 1) * nx + i + 1
                    
                    self.write_line(f"{elem_id}, {n1}, {n2}, {n3}, {n4}, {n5}, {n6}, {n7}, {n8}")
                    elem_id += 1
                    
        self.write_line("")
        return elem_id - 1
        
    def write_sets(self, nx, ny, nz=None):
        """Write node sets for probes and surfaces"""
        self.write_comment("NODE SETS")
        self.write_line("")
        
        if nz is None:  # 2D case
            # Probe sets
            probe_in_nodes = []
            probe_out_nodes = []
            
            # Find nodes near x=1.0 and x=9.0
            for j in range(ny):
                for i in range(nx):
                    x = i * 0.1  # Assuming element_size = 0.1
                    node_id = j * nx + i + 1
                    
                    if abs(x - 1.0) < 0.05:
                        probe_in_nodes.append(node_id)
                    elif abs(x - 9.0) < 0.05:
                        probe_out_nodes.append(node_id)
            
            # Write probe sets
            if probe_in_nodes:
                self.write_line("*NSET, NSET=PROBE_IN")
                for i, node_id in enumerate(probe_in_nodes):
                    if i % 8 == 0:
                        self.write_line(f"{node_id},")
                    else:
                        self.write_line(f"{node_id},", end="")
                self.write_line("")
                
            if probe_out_nodes:
                self.write_line("*NSET, NSET=PROBE_OUT")
                for i, node_id in enumerate(probe_out_nodes):
                    if i % 8 == 0:
                        self.write_line(f"{node_id},")
                    else:
                        self.write_line(f"{node_id},", end="")
                self.write_line("")
        else:  # 3D case
            # Similar logic for 3D
            pass
            
    def write_sections(self, materials):
        """Write section assignments"""
        self.write_comment("SECTION DEFINITIONS")
        self.write_line("")
        
        for i, material in enumerate(materials):
            mat_name = f"ACOUSTIC_{i+1}"
            self.write_line(f"*SOLID SECTION, ELSET=LAYER_{i+1}, MATERIAL={mat_name}")
            self.write_line("")
            
    def write_gradient_section(self):
        """Write section for gradient material"""
        self.write_comment("GRADIENT SECTION")
        self.write_line("")
        self.write_line("*SOLID SECTION, ELSET=ALL_ELEMENTS, MATERIAL=ACOUSTIC_GRADIENT")
        self.write_line("")
        
    def write_initial_conditions(self):
        """Write initial conditions for field variables"""
        self.write_comment("INITIAL CONDITIONS")
        self.write_line("")
        self.write_line("*INITIAL CONDITIONS, TYPE=FIELD")
        self.write_line("ALL_ELEMENTS, 1")
        self.write_line("")
        
    def write_step(self, freq_start=100, freq_end=5000, freq_inc=25):
        """Write Steady-State Dynamics step"""
        self.write_comment("STEADY-STATE DYNAMICS STEP")
        self.write_line("")
        self.write_line("*STEP, NAME=SSD, NLGEOM=NO")
        self.write_line("*STEADY STATE DYNAMICS, DIRECT")
        self.write_line(f"{freq_start}, {freq_end}, {freq_inc}")
        self.write_line("")
        
    def write_incident_wave(self, density=1025.0, sound_speed=1500.0):
        """Write incident wave definition"""
        self.write_comment("INCIDENT WAVE")
        self.write_line("")
        self.write_line("*INCIDENT WAVE INTERACTION PROPERTY, NAME=PLANEWAVE")
        self.write_line("*INCIDENT WAVE FLUID PROPERTY")
        self.write_line(f"{density}, {sound_speed}")
        self.write_line("")
        self.write_line("*INCIDENT WAVE INTERACTION, NAME=INC1, PROPERTY=PLANEWAVE")
        self.write_line("INLET_SURFACE, 1., 0., 0.")
        self.write_line("")
        
    def write_impedance_boundaries(self):
        """Write impedance boundary conditions"""
        self.write_comment("IMPEDANCE BOUNDARIES")
        self.write_line("")
        self.write_line("*IMPEDANCE, TYPE=NONREFLECTING")
        self.write_line("OUTLET_SURFACE,")
        self.write_line("")
        
    def write_output_requests(self):
        """Write output requests"""
        self.write_comment("OUTPUT REQUESTS")
        self.write_line("")
        self.write_line("*OUTPUT, FIELD, FREQUENCY=1")
        self.write_line("*NODE OUTPUT")
        self.write_line("P")
        self.write_line("")
        self.write_line("*OUTPUT, HISTORY, FREQUENCY=1")
        self.write_line("*NODE PRINT, NSET=PROBE_IN")
        self.write_line("P")
        self.write_line("*NODE PRINT, NSET=PROBE_OUT")
        self.write_line("P")
        self.write_line("")
        
    def write_end_step(self):
        """Write end step"""
        self.write_line("*END STEP")
        
    def save_file(self):
        """Save the input file"""
        with open(self.filename, 'w') as f:
            for line in self.lines:
                f.write(line + '\n')
        print(f"Input file saved: {self.filename}")


def generate_layered_2d_example():
    """Generate 2D layered example input file"""
    print("Generating 2D layered example...")
    
    generator = AbaqusInputGenerator("layered_2d_example.inp")
    
    # Header
    generator.write_heading("2D Layered Acoustic Transmission Loss")
    
    # Materials
    materials = [
        {'density': 1025.0, 'bulk_modulus': 2.306e9},
        {'density': 980.0, 'bulk_modulus': 2.162e9}
    ]
    generator.write_materials(materials)
    
    # Geometry (2D)
    length, width = 10.0, 2.0
    element_size = 0.1
    nx, ny = generator.write_nodes_2d(length, width, element_size)
    generator.write_elements_2d(nx, ny)
    
    # Sets
    generator.write_sets(nx, ny)
    
    # Sections
    generator.write_sections(materials)
    
    # Step
    generator.write_step()
    
    # Incident wave
    generator.write_incident_wave()
    
    # Impedance boundaries
    generator.write_impedance_boundaries()
    
    # Output
    generator.write_output_requests()
    
    # End
    generator.write_end_step()
    
    generator.save_file()


def generate_gradient_3d_example():
    """Generate 3D gradient example input file"""
    print("Generating 3D gradient example...")
    
    generator = AbaqusInputGenerator("gradient_3d_example.inp")
    
    # Header
    generator.write_heading("3D Gradient Acoustic Transmission Loss")
    
    # Gradient material
    generator.write_gradient_material(
        base_density=1025.0,
        base_bulk_modulus=2.306e9,
        density_gradient=-45.0,
        bulk_modulus_gradient=-0.144e9,
        z_range=(0, 1),
        n_points=20
    )
    
    # Geometry (3D)
    length, width, height = 10.0, 2.0, 1.0
    element_size = 0.1
    nx, ny, nz = generator.write_nodes_3d(length, width, height, element_size)
    generator.write_elements_3d(nx, ny, nz)
    
    # Sets
    generator.write_sets(nx, ny, nz)
    
    # Gradient section
    generator.write_gradient_section()
    
    # Initial conditions for field variables
    generator.write_initial_conditions()
    
    # Step
    generator.write_step()
    
    # Incident wave
    generator.write_incident_wave()
    
    # Impedance boundaries
    generator.write_impedance_boundaries()
    
    # Output
    generator.write_output_requests()
    
    # End
    generator.write_end_step()
    
    generator.save_file()


if __name__ == "__main__":
    print("="*60)
    print("ABAQUS INPUT FILE GENERATOR")
    print("="*60)
    
    # Generate examples
    generate_layered_2d_example()
    generate_gradient_3d_example()
    
    print("\nInput files generated successfully!")
    print("Files created:")
    print("  - layered_2d_example.inp")
    print("  - gradient_3d_example.inp")