# Nigerian states and regions mapping
NIGERIAN_STATES = [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno",
    "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "Gombe", "Imo", "Jigawa",
    "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger",
    "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe",
    "Zamfara", "FCT"  # Federal Capital Territory
]

STATE_TO_REGION = {
    "Abia": "South East",
    "Adamawa": "North East",
    "Akwa Ibom": "South South",
    "Anambra": "South East",
    "Bauchi": "North East",
    "Bayelsa": "South South",
    "Benue": "North Central",
    "Borno": "North East",
    "Cross River": "South South",
    "Delta": "South South",
    "Ebonyi": "South East",
    "Edo": "South South",
    "Ekiti": "South West",
    "Enugu": "South East",
    "Gombe": "North East",
    "Imo": "South East",
    "Jigawa": "North West",
    "Kaduna": "North West",
    "Kano": "North West",
    "Katsina": "North West",
    "Kebbi": "North West",
    "Kogi": "North Central",
    "Kwara": "North Central",
    "Lagos": "South West",
    "Nasarawa": "North Central",
    "Niger": "North Central",
    "Ogun": "South West",
    "Ondo": "South West",
    "Osun": "South West",
    "Oyo": "South West",
    "Plateau": "North Central",
    "Rivers": "South South",
    "Sokoto": "North West",
    "Taraba": "North East",
    "Yobe": "North East",
    "Zamfara": "North West",
    "FCT": "North Central",
}
